import { InstallRancherAIServiceArgs } from '@/cypress/globals';

/**
 * Installs Rancher AI to the local cluster using the kubeconfig generated by Rancher.
 */
Cypress.Commands.add('installRancherAIService', ( args: InstallRancherAIServiceArgs = { waitForAIServiceReady: true }) => {
  const wait = args.waitForAIServiceReady;

  return cy.getCookie('CSRF').then((token) => {
    cy.request({
      method:  'POST',
      url:     '/v3/clusters/local?action=generateKubeconfig',
      headers: {
        'x-api-csrf': token.value,
        Accept:       'application/json'
      },
    }).then((resp) => {
      expect(resp.status).to.eq(200);

      const kubeconfig = `${ Cypress.config('downloadsFolder') }/local.yaml`;

      cy.writeFile(kubeconfig, resp.body.config);

      const cmd = `.github/scripts/deploy-rancher-ai.sh ${ kubeconfig }${ wait ? '' : ' false' }`;

      cy.log('Cmd to execute:', cmd, 'flag: waitForAIServiceReady =', wait);

      cy.exec(cmd, {
        failOnNonZeroExit: false,
        timeout:           240000
      }).then((result) => {
        if (wait) {
          cy.log(`Script output: ${ result.stdout || 'None' }`);
          cy.log(`Script error: ${ result.stderr || 'None' }`);

          expect(result.code).to.eq(0);
        }
      });
    });
  });
});

/**
 * Uninstalls Rancher AI from the local cluster.
 */
Cypress.Commands.add('uninstallRancherAIService', () => {
  return cy.getCookie('CSRF').then((token) => {
    cy.request({
      method:  'POST',
      url:     '/v3/clusters/local?action=generateKubeconfig',
      headers: {
        'x-api-csrf': token.value,
        Accept:       'application/json'
      },
    }).then((resp) => {
      expect(resp.status).to.eq(200);

      const kubeconfig = `${ Cypress.config('downloadsFolder') }/local.yaml`;

      cy.writeFile(kubeconfig, resp.body.config);

      const cmd = `.github/scripts/uninstall-rancher-ai.sh ${ kubeconfig }`;

      cy.exec(cmd, {
        failOnNonZeroExit: false,
        timeout:           240000
      }).then((result) => {
        cy.log(`Script output: ${ result.stdout || 'None' }`);
        cy.log(`Script error: ${ result.stderr || 'None' }`);

        expect(result.code).to.eq(0);
      });

      // Wait some time for the uninstalled schemas to be removed from Rancher
      cy.wait(2000);
    });
  });
});