<script setup lang="ts">
import { computed, type PropType } from 'vue';
import { useStore } from 'vuex';
import { useI18n } from '@shell/composables/useI18n';
import { warn } from '../../utils/log';
import RcButton from '@components/RcButton/RcButton.vue';
import { ConfirmationStatus, ConfirmationActionType, MessageConfirmation } from '../../types';

const store = useStore();
const { t } = useI18n(store);

const props = defineProps({
  value: {
    type:    Object as PropType<MessageConfirmation>,
    default: () => ({} as MessageConfirmation),
  },
  messageContent: {
    type:    String,
    default: ''
  }
});

const emit = defineEmits(['confirm']);

// TODO the description should be generated by the backend
const confirmationText = computed(() => {
  const msg = t('ai.confirmation.message.question');

  try {
    if (!props.messageContent) {
      let out = '';

      props.value.actions?.forEach((action) => {
        const actionType = action?.type || ConfirmationActionType.Create;

        const {
          kind, name, namespace, cluster
        } = action?.resource || {};

        if (kind && name && namespace && cluster) {
          switch (actionType) {
          case ConfirmationActionType.Create:
            out += `${ t(`ai.confirmation.message.operation.create.description`, {
              name,
              kind,
              namespace,
              cluster,
              value: JSON.stringify(action.payload)
            }, true)  }<br>`;
            break;
          case ConfirmationActionType.Update:
          case ConfirmationActionType.Patch:
            const description = action?.payload?.reduce((acc: string, curr) => {
              const { op, value, path } = curr || {};

              if (op && value && path) {
                return `${ acc + t(`ai.confirmation.message.operation.update.description`, {
                  op,
                  value: typeof value === 'string' ? value : JSON.stringify(value),
                  path,
                  name,
                  kind,
                  namespace,
                  cluster
                }, true) }<br>`;
              }

              return acc;
            }, '');

            if (!!description?.trim()) {
              out += `${ description }<br>`;
            }
            break;
          }
        }
      });

      return `${ out }${ msg }`;
    }
  } catch (e) {
    warn('Error generating confirmation description:', e);
  }

  return msg;
});
</script>

<template>
  <div class="confirmation-action">
    <div class="confirmation-message">
      <span
        v-clean-html="confirmationText"
        data-testid="rancher-ai-ui-chat-message-confirmation-message"
      />
    </div>
    <div
      v-if="props.value.status === ConfirmationStatus.Pending"
      class="confirmation-buttons"
    >
      <div
        v-if="props.value.actions?.some(action => action.type === ConfirmationActionType.Delete)"
        class="delete-confirmation"
      >
        <!-- TODO Delete confirmation buttons -->
      </div>
      <div
        v-else
        class="standard-confirmation"
      >
        <RcButton
          small
          tertiary
          data-testid="rancher-ai-ui-chat-message-confirmation-cancel-button"
          @click="emit('confirm', false)"
        >
          <span class="rc-button-label">
            {{ t('ai.confirmation.cancel') }}
          </span>
        </RcButton>
        <RcButton
          small
          tertiary
          data-testid="rancher-ai-ui-chat-message-confirmation-confirm-button"
          @click="emit('confirm', true)"
        >
          <span class="rc-button-label">
            {{ t('ai.confirmation.confirm') }}
          </span>
        </RcButton>
      </div>
    </div>
    <div
      v-else
      class="confirmation-status"
    >
      <template v-if="props.value.status === ConfirmationStatus.Confirmed">
        <div
          class="status-confirmed"
          data-testid="rancher-ai-ui-chat-message-confirmation-confirmed"
        >
          <i class="icon icon-checkmark" />
          <p>
            {{ t('ai.confirmation.confirmed') }}
          </p>
        </div>
      </template>
      <template v-else-if="props.value.status === ConfirmationStatus.Canceled">
        <div
          class="status-canceled"
          data-testid="rancher-ai-ui-chat-message-confirmation-canceled"
        >
          <i class="icon icon-close canceled" />
          <p>
            {{ t('ai.confirmation.canceled') }}
          </p>
        </div>
      </template>
    </div>
  </div>
</template>

<style lang='scss' scoped>
.confirmation-message {
  margin-bottom: 12px;

  &:deep(code) {
    padding: initial;
    border: initial;
    border-radius: initial;
    background-color: transparent;
    color: #025937;
  }

  span {
    word-break: break-word;
    white-space: pre-line;
    list-style-position: inside;
  }
}

.confirmation-buttons, .standard-confirmation, .delete-confirmation {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}

.confirmation-status {
  .status-confirmed , .status-canceled {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: 4px;
    justify-content: flex-end;
  }

  .status-confirmed {
    .icon {
      color: var(--success);
    }
  }
  .status-canceled {
    .icon {
      color: var(--error);
    }
  }
}

.rc-button-label {
  word-break: break-word;
  white-space: pre-line;
  list-style-position: inside;
}
</style>